# Import libraries

In [6]:
import numpy as np

# Implement Spectral Decomposition

In [7]:
def spectral_decomposition(X):
    S, V = np.linalg.eig(X)
    VT = V.T

    return V, S, VT

# Rebuild X with K components using Spectral Decomposition

In [8]:
def rebuild_spectral_decomposition(V, S, VT, X, k):
    sort_indices = np.argsort(S)[::-1]
    S[::-1].sort()

    UT = VT[sort_indices]
    UT = UT[:k]
    U = UT.T

    Xrebuild = U @ UT @ X.T

    return Xrebuild.T

# Calculating the distortion

In [9]:
def distortion(X, X_rebuild):
    distortion = np.linalg.norm(X - X_rebuild, 2) ** 2

    return distortion

# Testing our implementation

In [10]:
X = np.array([[1, -2, 5, 4],
              [3, 2, 1, -5],
              [-10, 1, -4, 6]])

print("Original Matrix X:\n", X)

k = 2
A = X.T @ X

V, S, VT = spectral_decomposition(A)

X_rebuild = rebuild_spectral_decomposition(V, S, VT, X, k)

print("Reduced Matrix X:\n", X_rebuild)
print("The distortion:", distortion(X, X_rebuild))

Original Matrix X:
 [[  1  -2   5   4]
 [  3   2   1  -5]
 [-10   1  -4   6]]
Reduced Matrix X:
 [[ 1.31364626 -2.49821189  4.48223153  4.15965253]
 [ 3.67197174  0.93260544 -0.10929356 -4.65795229]
 [-9.70324553  0.5286199  -4.48988343  6.15105425]]
The distortion: 4.1516337722422545
